// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int N = Integer.parseInt(args[0]);
		int countGreater = 0;
		int countLessOrEqual = 0;

		for (int i = 0; i < N; i++){
			double x = Math.random();
			if (x > 0.5) countGreater++;
			if (x <= 0.5) countLessOrEqual++;
		}

		if (countGreater == 0  || countLessOrEqual == 0){
			System.out.println("> 0.5: " + countGreater + " times");
			System.out.println("<= 0.5: " + countLessOrEqual + " times");
		}

		else {
			double ratio = (double) countGreater / countLessOrEqual;
			System.out.println("> 0.5: " + countGreater + " times");
			System.out.println("<= 0.5: " + countLessOrEqual + " times");
			System.out.println("Ratio: " + ratio);

		}
	}
}

